[workspace]
resolver = "2"
members = [
    "day-*",
]

[workspace.dependencies]
anyhow = "1.0"
itertools = "0.12"
nom = "7.1"
nom_locate = "4.2"
indoc = "2.0"
rstest = "0.18"
glam = "0.24"
linked-hash-map = "0.5"
