[package]
name = "day-07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
itertools = "0.12"
nom = "7.1"
nom_locate = "4.2"
indoc = "2.0"
rstest = "0.18"
glam = "0.24"

